name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 1.0.1
homepage: https://github.com/luanpotter/audioplayers

flutter:
  plugin:
    platforms:
      android:
        default_package: audioplayers_android
      ios:
        pluginClass: AudioplayersPlugin

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  path_provider: ^2.0.1
  uuid: ^3.0.1

dev_dependencies:
  dartdoc: ^5.0.1
  flame_lint: ^0.1.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"