name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 0.20.0
homepage: https://github.com/luanpotter/audioplayers

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin
      ios:
        pluginClass: AudioplayersPlugin

dependencies:
  uuid:
  path_provider:
  http:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.2.1
  dartdoc: ^2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

